all: servidor cliente

servidor : servidor_u_cc.c
	gcc -Wall -Werror -pedantic -o servidor servidor_u_cc.c 

cliente : cliente_u_cc.c 
	gcc -g -Wall -Werror -pedantic -o cliente cliente_u_cc.c 

clean : 
	rm servidor cliente earth.jpg\
