all: servidor cliente

servidor : servidor_i_cc.c
	gcc -Wall -Werror -pedantic -o servidor servidor_i_cc.c 

cliente : cliente_i_cc.c 
	gcc -g -Wall -Werror -pedantic -o cliente cliente_i_cc.c 

clean : 
	rm servidor cliente earth.jpg\
